/* 内蔵プリセット — オフラインでも候補が出るように、有名な観光地・世界遺産を収録
   n: 名称 / k: 読み・別名(検索用) / c: 所在地 / lat,lng: 座標 / cat: カテゴリ / whc: 世界遺産 */
window.SPOT_PRESETS = [
  // ---- 日本 ----
  { n: '姫路城', k: 'ひめじじょう himeji castle 白鷺城', c: '日本 / 兵庫県姫路市', lat: 34.8394, lng: 134.6939, cat: 'castle', whc: true },
  { n: '法隆寺', k: 'ほうりゅうじ horyuji', c: '日本 / 奈良県斑鳩町', lat: 34.6148, lng: 135.7346, cat: 'temple', whc: true },
  { n: '厳島神社', k: 'いつくしまじんじゃ itsukushima 宮島', c: '日本 / 広島県廿日市市', lat: 34.2959, lng: 132.3197, cat: 'temple', whc: true },
  { n: '原爆ドーム', k: 'げんばくどーむ atomic bomb dome', c: '日本 / 広島県広島市', lat: 34.3955, lng: 132.4536, cat: 'monument', whc: true },
  { n: '東大寺', k: 'とうだいじ todaiji 大仏', c: '日本 / 奈良県奈良市', lat: 34.6890, lng: 135.8398, cat: 'temple', whc: true },
  { n: '清水寺', k: 'きよみずでら kiyomizudera', c: '日本 / 京都府京都市', lat: 34.9948, lng: 135.7850, cat: 'temple', whc: true },
  { n: '金閣寺（鹿苑寺）', k: 'きんかくじ kinkakuji', c: '日本 / 京都府京都市', lat: 35.0394, lng: 135.7292, cat: 'temple', whc: true },
  { n: '二条城', k: 'にじょうじょう nijo castle', c: '日本 / 京都府京都市', lat: 35.0142, lng: 135.7481, cat: 'castle', whc: true },
  { n: '日光東照宮', k: 'にっこうとうしょうぐう nikko toshogu', c: '日本 / 栃木県日光市', lat: 36.7580, lng: 139.5989, cat: 'temple', whc: true },
  { n: '白川郷 合掌造り集落', k: 'しらかわごう shirakawago', c: '日本 / 岐阜県白川村', lat: 36.2578, lng: 136.9066, cat: 'city', whc: true },
  { n: '屋久島', k: 'やくしま yakushima 縄文杉', c: '日本 / 鹿児島県', lat: 30.3428, lng: 130.5230, cat: 'nature', whc: true },
  { n: '知床', k: 'しれとこ shiretoko 知床五湖', c: '日本 / 北海道', lat: 44.1200, lng: 145.0800, cat: 'nature', whc: true },
  { n: '白神山地', k: 'しらかみさんち shirakami', c: '日本 / 青森県・秋田県', lat: 40.5000, lng: 140.1000, cat: 'nature', whc: true },
  { n: '富士山', k: 'ふじさん mount fuji fujisan', c: '日本 / 静岡県・山梨県', lat: 35.3606, lng: 138.7274, cat: 'nature', whc: true },
  { n: '熊野本宮大社', k: 'くまのほんぐうたいしゃ kumano 熊野古道', c: '日本 / 和歌山県田辺市', lat: 33.8400, lng: 135.7736, cat: 'temple', whc: true },
  { n: '高野山 金剛峯寺', k: 'こうやさん koyasan', c: '日本 / 和歌山県高野町', lat: 34.2131, lng: 135.5843, cat: 'temple', whc: true },
  { n: '首里城', k: 'しゅりじょう shuri castle', c: '日本 / 沖縄県那覇市', lat: 26.2170, lng: 127.7195, cat: 'castle', whc: true },
  { n: '軍艦島（端島）', k: 'ぐんかんじま hashima gunkanjima', c: '日本 / 長崎県長崎市', lat: 32.6277, lng: 129.7386, cat: 'monument', whc: true },
  { n: '中尊寺金色堂', k: 'ちゅうそんじ chusonji 平泉', c: '日本 / 岩手県平泉町', lat: 38.9930, lng: 141.0996, cat: 'temple', whc: true },
  { n: '富岡製糸場', k: 'とみおかせいしじょう tomioka silk mill', c: '日本 / 群馬県富岡市', lat: 36.2555, lng: 138.8878, cat: 'monument', whc: true },
  { n: '仁徳天皇陵古墳', k: 'にんとくてんのうりょう 百舌鳥 古市古墳群 daisen kofun', c: '日本 / 大阪府堺市', lat: 34.5644, lng: 135.4878, cat: 'monument', whc: true },
  { n: '石見銀山', k: 'いわみぎんざん iwami ginzan', c: '日本 / 島根県大田市', lat: 35.1150, lng: 132.4400, cat: 'monument', whc: true },
  { n: '伏見稲荷大社', k: 'ふしみいなり fushimi inari 千本鳥居', c: '日本 / 京都府京都市', lat: 34.9671, lng: 135.7727, cat: 'temple', whc: false },
  { n: '兼六園', k: 'けんろくえん kenrokuen', c: '日本 / 石川県金沢市', lat: 36.5622, lng: 136.6625, cat: 'park', whc: false },
  { n: '東京スカイツリー', k: 'とうきょうすかいつりー tokyo skytree', c: '日本 / 東京都墨田区', lat: 35.7101, lng: 139.8107, cat: 'monument', whc: false },

  // ---- アジア ----
  { n: '万里の長城（八達嶺）', k: 'ばんりのちょうじょう great wall badaling', c: '中国 / 北京市', lat: 40.3597, lng: 116.0201, cat: 'monument', whc: true },
  { n: '兵馬俑（秦始皇帝陵）', k: 'へいばよう terracotta army xian', c: '中国 / 西安市', lat: 34.3841, lng: 109.2785, cat: 'monument', whc: true },
  { n: '九寨溝', k: 'きゅうさいこう jiuzhaigou', c: '中国 / 四川省', lat: 33.2600, lng: 103.9200, cat: 'nature', whc: true },
  { n: 'タージ・マハル', k: 'たーじまはる taj mahal agra', c: 'インド / アーグラ', lat: 27.1751, lng: 78.0421, cat: 'monument', whc: true },
  { n: 'アンコール・ワット', k: 'あんこーるわっと angkor wat', c: 'カンボジア / シェムリアップ', lat: 13.4125, lng: 103.8670, cat: 'monument', whc: true },
  { n: 'ハロン湾', k: 'はろんわん ha long bay', c: 'ベトナム / クアンニン省', lat: 20.9101, lng: 107.1839, cat: 'nature', whc: true },
  { n: 'アユタヤ遺跡', k: 'あゆたや ayutthaya', c: 'タイ / アユタヤ', lat: 14.3532, lng: 100.5689, cat: 'monument', whc: true },
  { n: 'ボロブドゥール遺跡', k: 'ぼろぶどぅーる borobudur', c: 'インドネシア / ジャワ島', lat: -7.6079, lng: 110.2038, cat: 'monument', whc: true },
  { n: '昌徳宮', k: 'しょうとくきゅう changdeokgung', c: '韓国 / ソウル', lat: 37.5794, lng: 126.9910, cat: 'castle', whc: true },
  { n: '仏国寺', k: 'ぶっこくじ bulguksa 慶州', c: '韓国 / 慶州', lat: 35.7900, lng: 129.3320, cat: 'temple', whc: true },
  { n: 'ペトラ遺跡', k: 'ぺとら petra', c: 'ヨルダン / マアン県', lat: 30.3285, lng: 35.4444, cat: 'monument', whc: true },
  { n: 'イスタンブール歴史地区（アヤソフィア）', k: 'あやそふぃあ hagia sophia istanbul', c: 'トルコ / イスタンブール', lat: 41.0086, lng: 28.9802, cat: 'monument', whc: true },
  { n: 'カッパドキア', k: 'かっぱどきあ cappadocia goreme', c: 'トルコ / ネヴシェヒル県', lat: 38.6431, lng: 34.8289, cat: 'nature', whc: true },

  // ---- ヨーロッパ ----
  { n: 'コロッセオ', k: 'ころっせお colosseum roma', c: 'イタリア / ローマ', lat: 41.8902, lng: 12.4922, cat: 'monument', whc: true },
  { n: 'ヴェネツィア', k: 'べねちあ venice venezia', c: 'イタリア / ヴェネト州', lat: 45.4408, lng: 12.3155, cat: 'city', whc: true },
  { n: 'フィレンツェ歴史地区', k: 'ふぃれんつぇ florence firenze', c: 'イタリア / トスカーナ州', lat: 43.7696, lng: 11.2558, cat: 'city', whc: true },
  { n: 'ピサの斜塔', k: 'ぴさのしゃとう pisa', c: 'イタリア / ピサ', lat: 43.7230, lng: 10.3966, cat: 'monument', whc: true },
  { n: 'ポンペイ遺跡', k: 'ぽんぺい pompeii', c: 'イタリア / カンパニア州', lat: 40.7497, lng: 14.4869, cat: 'monument', whc: true },
  { n: 'アマルフィ海岸', k: 'あまるふぃ amalfi coast', c: 'イタリア / カンパニア州', lat: 40.6340, lng: 14.6027, cat: 'nature', whc: true },
  { n: 'ドロミーティ', k: 'どろみーてぃ dolomites', c: 'イタリア / 南チロル', lat: 46.4102, lng: 11.8440, cat: 'nature', whc: true },
  { n: 'サン・ピエトロ大聖堂', k: 'ばちかん vatican st peter', c: 'バチカン市国', lat: 41.9022, lng: 12.4539, cat: 'temple', whc: true },
  { n: 'サグラダ・ファミリア', k: 'さぐらだふぁみりあ sagrada familia barcelona', c: 'スペイン / バルセロナ', lat: 41.4036, lng: 2.1744, cat: 'temple', whc: true },
  { n: 'アルハンブラ宮殿', k: 'あるはんぶら alhambra granada', c: 'スペイン / グラナダ', lat: 37.1761, lng: -3.5881, cat: 'castle', whc: true },
  { n: 'シントラ', k: 'しんとら sintra ペーナ宮殿', c: 'ポルトガル / シントラ', lat: 38.7876, lng: -9.3904, cat: 'castle', whc: true },
  { n: 'ポルト歴史地区', k: 'ぽると porto', c: 'ポルトガル / ポルト', lat: 41.1408, lng: -8.6110, cat: 'city', whc: true },
  { n: 'モン・サン=ミシェル', k: 'もんさんみっしぇる mont saint michel', c: 'フランス / ノルマンディー', lat: 48.6361, lng: -1.5115, cat: 'monument', whc: true },
  { n: 'ヴェルサイユ宮殿', k: 'べるさいゆ versailles', c: 'フランス / ヴェルサイユ', lat: 48.8049, lng: 2.1204, cat: 'castle', whc: true },
  { n: 'エッフェル塔', k: 'えっふぇるとう eiffel tower paris', c: 'フランス / パリ', lat: 48.8584, lng: 2.2945, cat: 'monument', whc: true },
  { n: 'ストーンヘンジ', k: 'すとーんへんじ stonehenge', c: 'イギリス / ウィルトシャー', lat: 51.1789, lng: -1.8262, cat: 'monument', whc: true },
  { n: 'ロンドン塔', k: 'ろんどんとう tower of london', c: 'イギリス / ロンドン', lat: 51.5081, lng: -0.0759, cat: 'castle', whc: true },
  { n: 'ウェストミンスター寺院', k: 'うぇすとみんすたー westminster abbey', c: 'イギリス / ロンドン', lat: 51.4994, lng: -0.1273, cat: 'temple', whc: true },
  { n: 'ケルン大聖堂', k: 'けるんだいせいどう cologne cathedral', c: 'ドイツ / ケルン', lat: 50.9413, lng: 6.9583, cat: 'temple', whc: true },
  { n: 'ノイシュヴァンシュタイン城', k: 'のいしゅう゛ぁんしゅたいん neuschwanstein', c: 'ドイツ / バイエルン州', lat: 47.5576, lng: 10.7498, cat: 'castle', whc: false },
  { n: 'シェーンブルン宮殿', k: 'しぇーんぶるん schonbrunn vienna', c: 'オーストリア / ウィーン', lat: 48.1845, lng: 16.3122, cat: 'castle', whc: true },
  { n: 'ハルシュタット', k: 'はるしゅたっと hallstatt', c: 'オーストリア / 上オーストリア州', lat: 47.5622, lng: 13.6493, cat: 'city', whc: true },
  { n: 'プラハ歴史地区', k: 'ぷらは prague praha', c: 'チェコ / プラハ', lat: 50.0875, lng: 14.4213, cat: 'city', whc: true },
  { n: 'ブダペスト ドナウ河岸', k: 'ぶだぺすと budapest', c: 'ハンガリー / ブダペスト', lat: 47.4979, lng: 19.0402, cat: 'city', whc: true },
  { n: 'ドゥブロヴニク旧市街', k: 'どぅぶろう゛にく dubrovnik', c: 'クロアチア / ドゥブロヴニク', lat: 42.6407, lng: 18.1077, cat: 'city', whc: true },
  { n: 'アクロポリス（パルテノン神殿）', k: 'あくろぽりす acropolis parthenon athens', c: 'ギリシャ / アテネ', lat: 37.9715, lng: 23.7257, cat: 'monument', whc: true },
  { n: 'サントリーニ島', k: 'さんとりーに santorini', c: 'ギリシャ / キクラデス諸島', lat: 36.3932, lng: 25.4615, cat: 'nature', whc: false },
  { n: 'ブルッヘ歴史地区', k: 'ぶるっへ bruges brugge', c: 'ベルギー / ブルッヘ', lat: 51.2085, lng: 3.2247, cat: 'city', whc: true },
  { n: 'キンデルダイクの風車群', k: 'きんでるだいく kinderdijk', c: 'オランダ / 南ホラント州', lat: 51.8833, lng: 4.6400, cat: 'monument', whc: true },
  { n: 'ブリッゲン（ベルゲン）', k: 'ぶりっげん bryggen bergen', c: 'ノルウェー / ベルゲン', lat: 60.3975, lng: 5.3243, cat: 'city', whc: true },
  { n: 'ガイランゲルフィヨルド', k: 'がいらんげる geiranger fjord', c: 'ノルウェー / モーレ・オ・ロムスダール', lat: 62.1010, lng: 7.0055, cat: 'nature', whc: true },

  // ---- アメリカ大陸 ----
  { n: 'マチュ・ピチュ', k: 'まちゅぴちゅ machu picchu', c: 'ペルー / クスコ県', lat: -13.1631, lng: -72.5450, cat: 'monument', whc: true },
  { n: 'チチェン・イッツァ', k: 'ちちぇんいっつぁ chichen itza', c: 'メキシコ / ユカタン州', lat: 20.6829, lng: -88.5686, cat: 'monument', whc: true },
  { n: '自由の女神像', k: 'じゆうのめがみ statue of liberty new york', c: 'アメリカ / ニューヨーク', lat: 40.6892, lng: -74.0445, cat: 'monument', whc: true },
  { n: 'グランド・キャニオン国立公園', k: 'ぐらんどきゃにおん grand canyon', c: 'アメリカ / アリゾナ州', lat: 36.1069, lng: -112.1129, cat: 'nature', whc: true },
  { n: 'イエローストーン国立公園', k: 'いえろーすとーん yellowstone', c: 'アメリカ / ワイオミング州', lat: 44.4280, lng: -110.5885, cat: 'nature', whc: true },
  { n: 'ヨセミテ国立公園', k: 'よせみて yosemite', c: 'アメリカ / カリフォルニア州', lat: 37.8651, lng: -119.5383, cat: 'nature', whc: true },
  { n: 'バンフ国立公園', k: 'ばんふ banff canadian rockies', c: 'カナダ / アルバータ州', lat: 51.1784, lng: -115.5708, cat: 'nature', whc: true },
  { n: 'イグアスの滝', k: 'いぐあすのたき iguazu falls', c: 'アルゼンチン・ブラジル', lat: -25.6953, lng: -54.4367, cat: 'nature', whc: true },
  { n: 'ガラパゴス諸島', k: 'がらぱごす galapagos', c: 'エクアドル', lat: -0.7500, lng: -90.3167, cat: 'nature', whc: true },
  { n: 'ラパ・ヌイ（イースター島）', k: 'いーすたーとう rapa nui easter island moai', c: 'チリ', lat: -27.1127, lng: -109.3497, cat: 'monument', whc: true },

  // ---- アフリカ・オセアニア ----
  { n: 'ギザのピラミッド', k: 'ぴらみっど giza pyramid sphinx', c: 'エジプト / ギザ', lat: 29.9792, lng: 31.1342, cat: 'monument', whc: true },
  { n: 'ヴィクトリアの滝', k: 'う゛ぃくとりあのたき victoria falls', c: 'ザンビア・ジンバブエ', lat: -17.9243, lng: 25.8572, cat: 'nature', whc: true },
  { n: 'セレンゲティ国立公園', k: 'せれんげてぃ serengeti', c: 'タンザニア', lat: -2.3333, lng: 34.8333, cat: 'nature', whc: true },
  { n: 'キリマンジャロ国立公園', k: 'きりまんじゃろ kilimanjaro', c: 'タンザニア', lat: -3.0674, lng: 37.3556, cat: 'nature', whc: true },
  { n: 'ウルル（エアーズロック）', k: 'うるる uluru ayers rock', c: 'オーストラリア / ノーザンテリトリー', lat: -25.3444, lng: 131.0369, cat: 'nature', whc: true },
  { n: 'グレート・バリア・リーフ', k: 'ぐれーとばりありーふ great barrier reef', c: 'オーストラリア / クイーンズランド州', lat: -18.2871, lng: 147.6992, cat: 'nature', whc: true },
];
